// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableDualTitle": boolean;
      "displayMode": string;
      "titleOrder": string;
      "subtitleFontWeight": string;
      "translationFontSize": number;
      "translationColor": string;
      "translationGap": number;
      "autoTranslate": boolean;
      "rowHeightMultiplier": string;
      "childRowHeightMode": string;
    };
  }
}
